---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config-demo-secret
  namespace: restaurant-prod
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBBUbfSJCmHrEXQILwQw8FyXoY07nbPhXwC+YsqioJlh+8QLmFHYNg8BLMCOZ6bX8JlCSZdfwLGDogbVU3e3CpaAkGi6T+O8Em2V/hPHmUgZauApVAJnYh9EM95Li/VOnNGIxA6nC7w8sygQMOe8DJylPjd0AzXEQFeLbZNNcIYYeZ3sr5iodUo8pADTGM4b8XGM5Kch7gdPiSZ0h6jMcPAbx8cIvkqZ+sc/NMcBoPBXx2+4iLUCAKWeyVS28+Gb35MpXP+Qe1v2T10GnLeUBGvE/rEjUiXGVyDUg21LcgqW4F7lS2JVAkGz+44v1zRuP9BJq3RJQ54+LnpByv7Pk98JD4LqyFXx125OmMOgToBptPjXOhES47IyacDmZOzz9oiulsHEaIlCnn/4Bp0Abp/iJEroyBcgqqqvgfBmhIF1Jl6XS7tPnFc1qBXgkGk+FDfSel3HdWCulLk2Bi1AAT8DWootYfS3n6pyrjvh8ERuGmnsrF5vZpKBly8kHUTSaeI9Sqoy4Dn2Pmcusgh0TO4b3bJOQKGOA3gcw2Sx++4MaP7NNSKQOTOFqU7WJWIrbkqVpWON+Cu1sUK2wRjXdlzc55ngYf0LVn9PW3o3JC6Scqr6qviFABFlksV4+zNBsnlktdimQ/AZIzAeKaeHUCG3/KNJF3iK87C7Pkf34GzJT4JYYGhaG5himGBpM+piEc=
  template:
    metadata:
      name: config-demo-secret
      namespace: restaurant-prod
