---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config-demo-secret
  namespace: restaurant-prod
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBt16spO5FUjGdVjNQYuM03TxgsC35HNOZnQSMXcPqOj27tZfRw39ihnCBCet4RGvDXmsQwgxuIHwZcml6PJDVGKZbaidF/d2K99DiZs8lFKJ8ZUztMuWT48jGSZtMYsnjSAOOP/H3ni0BPzSYAwQw3VWVkUT+LFJV8m22pSBiiVRWerDetzl8R/EAv9Gy10v6sDPr197HIsqblU0H90RffcVdPwH+revxZnNGNq5f3Rfm/ixFNq4Tvck32OvkC0L7BhgJ+ZtX+zrBlj0UFAGo13XxA7tJFBs7wI2MEo0iY163mf8xCHlS9IDPbpACgUf/BSYfzgSPPwFVLWxVdGeRPgEUh7RnfyySDB0zCVbDrHHzBf34chEOA2qYPjvQckw2H3suom/OEr7TatQqGJnbRINHLjZe6XTr8kro8ay/9QxCsQBrTs2dhL75Cs6UA5PuQwK63BEyiFA8LMekPIB885Hk2LYY1GFmHCVaaZXcHGGsd0b6Mx59yj4+PO2SfXPnM5yLJ33da/ug1NI5Uu4TbMItU4gn8JbjBE4JRISYCobrG9Grig0yRo7k1VWG+89O7/6A6ZSpRFKaPOSsfL170azIxqHlaZz+AN/ICwIGtl/IvKTrXYTj8kCvKo0vXdf1rSgmok6gPxzce8yytXCnInFqmCH2H3dgErY4zzZjIohbGyU4v9V/dvxz6c1bPCKppSiPufYO639NWx++b
  template:
    metadata:
      name: config-demo-secret
      namespace: restaurant-prod
