apiVersion: v1
kind: ResourceQuota

metadata:
  name: restaurant-prod-quota

spec:
  hard:
    # Sammanlagda requests i hela namespacet.
    requests.cpu: "1"
    requests.memory: 1Gi

    # Sammanlagda limits i hela namespacet.
    limits.cpu: "2"
    limits.memory: 2Gi

    # Begränsa antalet resurser.
    pods: "10"
    services: "5"
    configmaps: "10"
    secrets: "10"
    persistentvolumeclaims: "2"

    count/deployments.apps: "5"
    count/ingresses.networking.k8s.io: "5"
