apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: restaurant
  namespace: argocd

  annotations:
    # Kräver uttryckligt godkännande innan Argo CD får radera projektet.
    argocd.argoproj.io/sync-options: Prune=confirm

spec:
  description: Argo CD project for the restaurant application environments.

  # Endast detta Git-repository får användas av projektet.
  sourceRepos:
    - https://github.com/linkmush/Restaurant_Template_2_Yaml.git

  # Projektets applikationer får endast installera till dessa namespaces.
  destinations:
    - namespace: restaurant-dev
      server: https://kubernetes.default.svc

    - namespace: restaurant-prod
      server: https://kubernetes.default.svc

  # Namespace är en klusteromfattande resurs.
  # Detta krävs eftersom våra overlays innehåller namespace.yaml.
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  # Tillåt namespacade resurser såsom Deployment, Service och Ingress.
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Varna om resurser finns i projektets namespaces men inte längre
  # hanteras av någon Argo CD Application.
  orphanedResources:
    warn: true

    # Registry-secretet hanteras manuellt i homelabbet
    # och ska därför inte visas som en orphaned resource.
    ignore:
      - group: ""
        kind: Secret
        name: ghcr-secret