apiVersion: v1
kind: Namespace

metadata:
  name: restaurant-prod

  labels:
    # Namespace-resursens funktion är att innehålla applikationer.
    purpose: applications

    # Anger vilken driftsmiljö detta namespace representerar.
    environment: prod

    # Namespace skiljer prod-miljön från test- och dev-miljöer.
    #
    # Här placeras bland annat:
    # - Deployment
    # - Service
    # - Ingress
    # - Pods
    # - Secrets
