apiVersion: apps/v1
kind: Deployment

metadata:
  name: restaurant-template
  labels:
    app: restaurant-template
    # environment=dev.(dev, test, prod)
    environment: dev # Märker själva Deployment-resursen som tillhörande dev-miljön. Används för att organisera och filtrera Deployments, exempelvis: kubectl get deployments -l environment=dev

spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: restaurant-template

  template:
    metadata:
      labels:
        app: restaurant-template
        # environment=dev.(dev, test, prod)
        environment: dev  # Märker alla Pods som Deploymenten skapar som dev-Pods. Labeln beskriver Poddens miljötillhörighet men styr inte placeringen i miljön.

    spec:
      nodeSelector:
        node-pool: applications # Podden får köras på noder som tillhör applications-gruppen.
        environment: dev # Podden får endast schemaläggas på en node märkt environment=dev.(dev, test, prod) Om ingen dev node är tillgänglig kommer Podden att bli Pending.

      containers:
        - name: restaurant-template
          image: ghcr.io/linkmush/restaurant-template:1.0

          ports:
            - name: http
              containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

      imagePullSecrets:
        - name: ghcr-secret