apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: restaurant-ingress

spec:
  ingressClassName: traefik

  rules:
    - host: linkmush.template

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: restaurant-service
                port:
                  number: 80