apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Restaurangapplikationens aktiva dev-miljö.
  - environments/dev

  # Tomt namespace reserverat för framtida övervakning.
  - platform/monitoring