apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homelab-observer-oskar
subjects:
  - kind: User
    name: oskar-homelab
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: homelab-observer
  apiGroup: rbac.authorization.k8s.io
