apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Read-only observer.
  - homelab-observer/homelab-observer-clusterrole.yaml
  - homelab-observer/homelab-observer-binding.yaml

  # Node maintenance.
  - homelab-maintenance/homelab-maintenance-clusterrole.yaml
  - homelab-maintenance/homelab-maintenance-binding.yaml
  - homelab-maintenance/homelab-maintenance-observer-binding.yaml

  # Incident responder.
  - incident@homelab/incident-responder-clusterrole.yaml
  - incident@homelab/incident-responder-binding.yaml
  - incident@homelab/incident-responder-observer-binding.yaml

