apiVersion: apps/v1
kind: Deployment

metadata:
  name: config-demo

  labels:
    environment: dev

spec:
  template:
    metadata:
      labels:
        environment: dev

    spec:
      nodeSelector:
        environment: dev
