apiVersion: v1
kind: Namespace

metadata:
  name: restaurant-dev

  labels:
    # Namespace-resursens funktion är att innehålla applikationer.
    purpose: applications

    # Anger vilken driftsmiljö detta namespace representerar.
    environment: dev

    # När Deploymenten fungerar med den nya SecurityContext-konfigurationen ändrar vi dev till:
    # pod-security.kubernetes.io/enforce: restricted
    # Prod får inte restricted förrän konfigurationen har verifierats i dev.
    # Stoppar de grövsta säkerhetsproblemen.
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest

    # Visa varning om podden inte klarar restricted.
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest

    # Registrera även avvikelser mot restricted.
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest

    # Namespace skiljer dev-miljön från framtida test- och prod-miljöer.
    #
    # Här placeras bland annat:
    # - Deployment
    # - Service
    # - Ingress
    # - Pods
    # - Secrets
