apiVersion: v1
kind: ServiceAccount

metadata:
  name: restaurant-app

# Kubernetes monterar annars normalt en API-token i podden.
# Applikationen behöver inte prata med Kubernetes API och får därför ingen token.
automountServiceAccountToken: false
