apiVersion: v1
kind: ServiceAccount

metadata:
  name: config-demo

  labels:
    app: config-demo
    app.kubernetes.io/name: config-demo
    app.kubernetes.io/component: configuration-demo

# Workloaden behöver inte prata med Kubernetes API.
automountServiceAccountToken: false
