---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config-demo-secret
  namespace: restaurant-dev
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCsBh6OXuAFkoCUCsEVRyYxanKjUznY1vQ9wmH2gePL51Sth7AgK6+eHJniTtZu6aQ/hg7PH4eO8atSmi4R1STbABHPK/MEPGJUb8c52Rjr+teHv7adeMlbG9EqgzmrV+BvJjwPkQzEi1bdXi6uro/IIWFi+mxv4XhEeFByh4AyDbYvwoawJ5mGl3hwofAGSHYCmoQJEZArX3prQ+8CV1DjKFv5X5Gp5KOvgmoFSNdSpnzOkdJcOfAVDOe2UdSfP1dRF5HffpZJ/IodCLp/EZPUYY+uWe5R1959MmLSvVFkt0zVR1NraEWeuGcIK63nJneYFCrrKlgN787052Z6OZsoIQIceQSPAHqLtct9GYXK8BoM8bW11vUTHmzQoab2V0qqByHtP9q0FzHZar9WjGAiyAGgz/V4c19Qf4slekP/QmCMR/Ci4znwG0s2HrkqumjAUF0694TJDDra3+hFt17di9luny4NbLryrBlytTlfkE/ACxQppPNXYl/GX99Lbuj4Xn7tOwbWnf4RRpWX5cBRz4XluKKd6Pdu8u2b5GmltM41QB6FNowSFhXq8QXkDfklKHj2i92lhqQAabaRMdcKtVLuv/OTvD9azCMF/grWcE4IhRr2NeSGiY9BtXcuLQD07KUNiIwaaQ+nhQPXHkJgvH740DIk0aGgxXpTgWeoz5DMPR1Smiej4yjyYp7V84B918OAmzd5J62ELoh7
  template:
    metadata:
      name: config-demo-secret
      namespace: restaurant-dev
