---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config-demo-secret
  namespace: restaurant-dev
spec:
  encryptedData:
    DATABASE_PASSWORD: AgA0G4e8mWbbhamYadbzafxbdm5JEKVtl+VmGl8UsCmEPXLOX34TjjtPIg6fTvFQVbs9GY0NoD9BrzRLkz6FRSJ009h+VMI1/i5wICSNxNswqBgCIaD2DitHaZs6twFE4KVz2D1BTy7bC/Q8b/CbVkS2NncHS6TqBUoHWjMMsP34UgKtnR93nPEFACrUxFfNGqPKgm8iKufz3P8yeUqI2vOcj5GPGqsxALTPH978s2nD8jGe/Sph4N/Ak1nnMAHxYhJzY1CTkh4ifGkrQm26tncemuD6ouxlkXnTFRRPctuRnSGKgmkF+GhNtICyBuiWg6Q5XzWQmLhSk3nrk7wmAAZAdvSy/SK7DJi+tGalL3MZ9i9A5yq15JTAtrGQ7TPfY374UlYX3Uh86XnR8yX8olSnb07E5Jh9VdKN/1Tr3r+hA/IebTcv0MHUxmj9XG1PmigEG0MHypxc+8lO086Ywfknn94OliITHmSjXSJuheY+em1p9JFMKWZoTbWgqsmN+a2vgAmYuNL3T1LTEc9rAx73xDMmDVTmpEfZnvaNCVwpBSMDtCn5IGl4fmWna3lqSDo78mLFRxVrVpqMvByR+P5Mu+PYklPQmZ5/c4GyrIGoC9KJAVRVOmCD+iNLw4dxDICqr4wdkX6fNK/L4Md+FFDCX49DUaUnpk0O2/5CohXRrU9VZ1wZmrzMXYP+rXidnMBw2cSUQvbPie3XUFLm
  template:
    metadata:
      name: config-demo-secret
      namespace: restaurant-dev
