apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: incident-responder

rules:

  # Får undersöka alla Kubernetes-resurser
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch

  # Får gå in i containers
  - apiGroups: [""]
    resources:
      - pods/exec
    verbs:
      - create

  # Får korrigera workloads
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - patch
      - update

  # Får korrigera Service, ConfigMap och Secrets
  - apiGroups: [""]
    resources:
      - services
      - configmaps
      - secrets
    verbs:
      - patch
      - update

  # Får korrigera Ingress och NetworkPolicy
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - patch
      - update
